async (page) => {
  const assert = (v, message) => {if(!v) throw Error(message)};
  await page.getByText('添加或纠正一条记忆',{exact:true}).click();
  await page.locator('#slot').fill('页面测试期限甲');
  await page.locator('#ttl').fill('3');
  await page.locator('#memoryText').fill('我计划每周三下午整理阳台植物，给兰花浇水，检查叶片并记录生长情况。');
  await page.getByRole('button',{name:'保存记忆',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('记忆已保存'));
  await page.locator('#slot').fill('页面测试期限乙');
  await page.locator('#ttl').fill('9');
  await page.locator('#memoryText').fill('我习惯把园艺工具放在阳台储物柜，周末会清洗花盆和擦拭柜子。');
  await page.getByRole('button',{name:'保存记忆',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.record').length>=2);
  const first=await page.evaluate(()=>records.find(r=>r.slot==='页面测试期限甲').expires);
  const rowA=page.locator('.record').filter({hasText:'页面测试期限甲'});
  await rowA.getByRole('button',{name:'纠正'}).click();
  assert(await page.locator('#ttl').inputValue()==='3','First expiry not loaded');
  await page.locator('#memoryText').fill('我现在计划每周四下午整理阳台植物，给兰花浇水。');
  await page.getByRole('button',{name:'保存记忆',exact:true}).click();
  await page.waitForFunction(()=>records.some(r=>r.slot==='页面测试期限甲'&&r.text.includes('周四')));
  assert(await page.evaluate(()=>records.find(r=>r.slot==='页面测试期限甲').expires)===first,'Exact expiry changed');
  await page.locator('.record').filter({hasText:'页面测试期限乙'}).getByRole('button',{name:'纠正'}).click();
  assert(await page.locator('#ttl').inputValue()==='9','Second expiry contaminated');
  const longText='这是用于页面布局验证的临时生活记录。'+('我喜欢在阳台照料兰花，给植物浇水后把工具放回储物柜。'.repeat(8));
  await page.locator('#slot').fill('页面测试长记录');
  await page.locator('#ttl').fill('1');
  await page.locator('#memoryText').fill(longText);
  await page.getByRole('button',{name:'保存记忆',exact:true}).click();
  await page.waitForFunction(()=>records.some(r=>r.slot==='页面测试长记录'));
  await page.locator('#speech').fill('我的阳台植物都有哪些需要照料的事？');
  await page.getByRole('button',{name:'发送',exact:true}).click();
  await page.waitForFunction(()=>!document.getElementById('send').disabled,{},{timeout:90000});
  await page.getByText('本轮识别与记忆来源',{exact:true}).click();
  await page.setViewportSize({width:1440,height:1000});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Desktop overflow');
  await page.screenshot({path:'output/playwright/v5-desktop-verified.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
  await page.screenshot({path:'output/playwright/v5-mobile-verified.png',fullPage:true});
  console.log(JSON.stringify({registered:true,save_edit:true,expiry_a:3,expiry_b:9,exact_expiry_preserved:true,desktop_mobile_overflow:false,long_detail_chars:await page.locator('#turnDetail').textContent().then(s=>s.length),camera_tested:false}));
}
