async (page) => {
 const assert=(condition,message)=>{if(!condition)throw Error(message)};
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.reload();
 await page.locator('#userMbti option[value="INFJ"]').waitFor({state:'attached'});
 await page.getByRole('combobox',{name:'我的 MBTI',exact:true}).selectOption('INFJ');
 await page.getByRole('combobox',{name:'现在希望怎样聊',exact:true}).selectOption('listen');
 assert((await page.locator('#personalityState').innerText()).includes('INFJ'),'Selection summary absent');
 assert(await page.getByRole('button',{name:'保存偏好，下次沿用',exact:true}).isDisabled(),'Guest can save');
 await page.getByRole('button',{name:'今天有点累',exact:true}).click();
 assert((await page.getByLabel('想说的话',{exact:true}).inputValue()).includes('今天有点累'),'Starter not copied');
 assert(await page.locator('.message').count()===0,'Starter submitted without send');
 const reply=page.waitForResponse(r=>r.url().endsWith('/v1/step')&&r.request().method()==='POST');
 await page.getByRole('button',{name:'发送',exact:true}).click();
 const generated=await (await reply).json();
 assert(generated.state.dialogue_profile.mbti==='INFJ','UI preference did not reach model');
 assert(generated.state.dialogue_profile.support==='listen','Need preference missing');
 await page.getByRole('button',{name:'发送',exact:true}).waitFor();
 await page.setViewportSize({width:1440,height:1000});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Desktop overflow');
 await page.locator('.personality-setup').screenshot({path:'output/playwright/mbti-desktop.png'});
 await page.setViewportSize({width:390,height:844});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');
 await page.locator('.personality-setup').screenshot({path:'output/playwright/mbti-mobile.png'});
 await page.locator('.conversation-preferences').screenshot({path:'output/playwright/mbti-starters-mobile.png'});
 await page.getByRole('button',{name:'暂不设定 MBTI',exact:true}).click();
 assert(await page.getByRole('combobox',{name:'我的 MBTI',exact:true}).inputValue()==='','Skip failed');
 const uid='mbti_ui_'+Date.now();
 await page.getByLabel('成员 ID',{exact:true}).fill(uid);
 await page.getByLabel('成员 PIN（至少 6 位）',{exact:true}).fill('temporary-check-pin');
 await page.getByLabel('显示名称（首次登记）',{exact:true}).fill('临时偏好验证');
 await page.getByRole('button',{name:'新建成员',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('setupHint').textContent.includes('登录成功'));
 await page.getByRole('combobox',{name:'我的 MBTI',exact:true}).selectOption('INTJ');
 await page.getByLabel('允许保存我的长期记忆',{exact:false}).check();
 assert(await page.getByRole('button',{name:'保存偏好，下次沿用',exact:true}).isDisabled(),'Unconfirmed consent enabled save');
 await page.getByRole('button',{name:'更新记忆许可',exact:true}).click();
 await page.waitForFunction(()=>!document.getElementById('savePersonality').disabled);
 await page.getByRole('button',{name:'保存偏好，下次沿用',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('personalityReceipt').textContent.includes('偏好已保存'));
 await page.getByRole('button',{name:'退出',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('userMbti').value==='');
 await page.getByLabel('成员 PIN（至少 6 位）',{exact:true}).fill('temporary-check-pin');
 await page.getByRole('button',{name:'登录',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('userMbti').value==='INTJ');
 await page.getByText('数据管理',{exact:true}).click();
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'清空我的记忆',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('userMbti').value==='');
 page.once('dialog',dialog=>dialog.accept());
 await page.getByRole('button',{name:'删除我的成员资料',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('currentMember').textContent==='访客');
 assert(errors.length===0,errors.join('\n'));
 return {desktop:'1440x1000',mobile:'390x844',overflow:false,guest_send:true,consent_gate:true,saved_and_reloaded:true,forgotten_and_deleted:true,page_errors:errors,reply:generated.response};
}

