async page => {
 const checks=[],errors=[];
 const assert=(ok,msg)=>{if(!ok)throw Error(msg);checks.push(msg)};
 page.on('pageerror',e=>errors.push(e.message));
 const click=id=>page.locator('#'+id).click();
 const step=async n=>{await page.locator(`[data-step="${n}"]`).waitFor({state:'visible'});assert(await page.locator('[data-step]:visible').count()===1,'only step '+n+' visible')};
 const fit=async(label)=>{const v=await page.evaluate(()=>({width:document.documentElement.scrollWidth<=innerWidth,height:document.documentElement.scrollHeight<=innerHeight,footer:(()=>{const r=document.getElementById('confirmSetup').getBoundingClientRect();return r.bottom<=innerHeight&&r.right<=innerWidth})()}));assert(v.width&&v.height&&v.footer,label+' viewport and actions fit')};
 await page.reload();await page.waitForFunction(()=>window.voiceConversation);await page.setViewportSize({width:1440,height:900});await step(1);await fit('desktop login');await page.screenshot({path:'output/playwright/guided-login-desktop.png'});
 await page.setViewportSize({width:390,height:844});await fit('mobile login');await page.screenshot({path:'output/playwright/guided-login-mobile.png'});
 await click('login');assert((await page.locator('#loginHint').innerText()).includes('至少 6 位'),'inline login validation');
 await click('guestContinue');await step(2);assert(await page.locator('#consent').isDisabled(),'guest cannot save memory');await page.locator('#cameraConsent').uncheck();await click('confirmSetup');await step(3);
 await page.locator('#voiceChoice').selectOption('zh-CN-XiaoxiaoNeural');assert((await page.locator('#confirmSetup').innerText()).includes('同意在线朗读'),'online voice action explicitly asks consent');assert(!(await page.locator('#cloudVoiceConsent').isChecked()),'choosing voice does not grant consent');await click('confirmSetup');await step(4);assert(await page.locator('#cloudVoiceConsent').isChecked(),'explicit consent action advances');await click('previousStep');await step(3);
 await page.locator('#voiceChoice').selectOption('device');await click('confirmSetup');await step(4);await page.waitForFunction(()=>document.getElementById('serviceCheckStatus').textContent.includes('已就绪'));await fit('mobile devices');await page.screenshot({path:'output/playwright/guided-devices-mobile.png'});
 await click('confirmSetup');assert(await page.locator('#workspace').isHidden(),'unprepared voice does not enter');
 await page.evaluate(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('denied','NotAllowedError')}});await click('testMic');await page.waitForFunction(()=>document.getElementById('micCheckStatus').textContent.includes('未允许'));checks.push('microphone denial actionable');
 await click('fallbackText');await page.waitForFunction(()=>document.getElementById('serviceCheckStatus').textContent.includes('已就绪'));await click('confirmSetup');await page.locator('#workspace').waitFor({state:'visible'});assert(await page.locator('#setupPanel').isHidden(),'wizard replaced by conversation');assert(await page.locator('#liveVoicePanel').isHidden(),'text fallback hides voice controls');await fit('mobile conversation');await page.screenshot({path:'output/playwright/guided-chat-mobile.png'});
 await page.setViewportSize({width:1440,height:900});await fit('desktop conversation');await page.screenshot({path:'output/playwright/guided-chat-desktop.png'});
 await page.setViewportSize({width:1366,height:768});await fit('laptop conversation');assert(await page.locator('#send').isVisible(),'composer visible');
 await page.locator('#speech').fill('你好，请用一句话向我打个招呼。');await page.locator('#speech').press('Enter');await page.waitForFunction(()=>document.querySelectorAll('#chatLog .message').length>=2&&!document.getElementById('send').disabled,null,{timeout:60000});assert(!(await page.locator('#chatLog').innerText()).includes('本轮未完成'),'real model text reply');
 await click('manageMemory');assert(await page.locator('#memoryControls').isHidden(),'guest memory has clear empty state');await click('closeMemory');await click('openSettings');await click('editPersonality');await step(3);await click('previousStep');await step(2);
 await page.reload();await page.waitForFunction(()=>window.voiceConversation);await click('toggleRegister');const uid='ui_flow_'+Date.now();await page.locator('#uid').fill(uid);await page.locator('#pin').fill('guide-test-123');await page.locator('#name').fill('引导流程测试');await click('register');await step(2);const memberToken=await page.evaluate(()=>token);
 try{
  await click('previousStep');await step(1);assert(await page.locator('#loggedIdentity').isVisible(),'back keeps authenticated identity');assert(await page.locator('#loginEntry').isHidden(),'no duplicate login required');await click('continueIdentity');await step(2);
  await page.locator('#consent').check();await page.locator('#cameraConsent').uncheck();await click('confirmSetup');await step(3);await page.locator('#modeText').check();await click('confirmSetup');await step(4);await page.waitForFunction(()=>document.getElementById('serviceCheckStatus').textContent.includes('已就绪'));await click('confirmSetup');await page.locator('#workspace').waitFor({state:'visible'});
  await click('manageMemory');await page.locator('#editor summary').click();await page.locator('#slot').fill('界面测试位置');await page.locator('#memoryText').fill('测试钥匙放在书房抽屉。');await click('saveMemory');await page.waitForFunction(()=>document.getElementById('records').textContent.includes('测试钥匙'));await click('closeMemory');assert((await page.locator('#memoryPreview').innerText()).includes('测试钥匙'),'saved memory appears below conversation');
  await click('openSettings');await click('logout');await step(1);await page.locator('#uid').fill(uid);await page.locator('#pin').fill('guide-test-123');if(await page.locator('#login').isHidden())await click('toggleRegister');await click('login');await step(2);assert(await page.locator('#consent').isChecked(),'existing member login loads consent');assert(!(await page.locator('#memoryPreview').innerText()).includes('访客'),'member memory restored');
 }finally{const r=await page.request.delete('http://127.0.0.1:8768/v1/member',{headers:{'X-Member-Session':await page.evaluate(()=>token)||memberToken}});assert(r.ok(),'test member cleanup');await page.reload()}
 assert(errors.length===0,'no browser runtime errors');return {checks,errors};
}
